### ISSUE TITLE
npx prisma db push not working  

### ISSUE THREAD

**Issue by Shubhodeep100** [ski043/Marshal-Saas#1]
![Screenshot 2024-02-10 163535](https://github.com/ski043/Marshal-Saas/assets/96099026/c0afef34-05e4-455f-98d8-863c466488d4)

I followed each and every step properly of providing the UTI of the "DIRECT_URL" with the exact port no.(as shown in the tutorial.) Still I'm getting an error on running the CLI `npx prisma db push`

@ski043 Could you please share any update or any fix of  the issue.
Facing the problem at [**01:33:87**](url) of the tutorial. Can anyone please help me resolve the issue of this Supabase with postgres?? 
Thank you in advance.

**Comment by ski043** [comment]
https://supabase.com/partners/integrations/prisma

Check if you did it correctly

**Comment by Shubhodeep100** [comment]
![Screenshot 2024-02-10 170357](https://github.com/ski043/Marshal-Saas/assets/96099026/20a17d27-ee99-4ad4-8a2f-1b1b92da3478)

![Screenshot 2024-02-10 170057](https://github.com/ski043/Marshal-Saas/assets/96099026/b8100ef3-27fd-4087-a7f0-3c6913e7366c)
@ski043 
Did exactly the same with the correct port no. with reference to the docx. The error still persists.

**Comment by blocksdevpro** [comment]
When pushing the schema to the db, try using the DATABASE_URL & DIRECT_URL without  the ```":6532/postgress?pgbouncer=true&conection_limit=1"```:

```python
# not this
DATABASE_URL = "postgres://postgres.qzshylushurbreqcebld:<PASSWORD>@aws-0-eu-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1"
DIRECT_URL = "postgres://postgres.qzshylushurbreqcebld:<PASSWORD>@aws-0-eu-west-1.pooler.supabase.com:5432/postgres"

# edit this 
DATABASE_URL = "postgres://postgres.qzshylushurbreqcebld:<PASSWORD>@aws-0-eu-west-1.pooler.supabase.com"
DIRECT_URL = "postgres://postgres.qzshylushurbreqcebld:<PASSWORD>@aws-0-eu-west-1.pooler.supabase.com"


```

**Comment by Shubhodeep100** [comment]
> When pushing the schema to the db, try using the DATABASE_URL & DIRECT_URL without the `":6532/postgress?pgbouncer=true&conection_limit=1"`:
> 
> ```python
> # not this
> DATABASE_URL = "postgres://postgres.qzshylushurbreqcebld:<PASSWORD>@aws-0-eu-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1"
> DIRECT_URL = "postgres://postgres.qzshylushurbreqcebld:<PASSWORD>@aws-0-eu-west-1.pooler.supabase.com:5432/postgres"
> 
> # edit this 
> DATABASE_URL = "postgres://postgres.qzshylushurbreqcebld:<PASSWORD>@aws-0-eu-west-1.pooler.supabase.com"
> DIRECT_URL = "postgres://postgres.qzshylushurbreqcebld:<PASSWORD>@aws-0-eu-west-1.pooler.supabase.com
